
package co.com.claro.wsresourcehomepass.implement;

import co.com.claro.wsresourcehomepass.service.Service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSResourceHomePass", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/", wsdlLocation = "http://172.24.42.24:8600/WSResourceHomePass/WSResourceHomePass?wsdl")
public class WSResourceHomePass
    extends javax.xml.ws.Service
{


    private final static QName WSRESOURCEHOMEPASS_QNAME = new QName("http://implement.wsresourcehomepass.claro.com.co/", "WSResourceHomePass");



    public WSResourceHomePass(URL wsdlLocation) {
        super(wsdlLocation, WSRESOURCEHOMEPASS_QNAME);
    }

    public WSResourceHomePass(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSRESOURCEHOMEPASS_QNAME, features);
    }

    public WSResourceHomePass(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSResourceHomePass(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort() {
        return super.getPort(new QName("http://implement.wsresourcehomepass.claro.com.co/", "ServicePort"), Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://implement.wsresourcehomepass.claro.com.co/", "ServicePort"), Service.class, features);
    }



}
