
package co.com.claro.ejb.mgl.ws.client.updateCaseStatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPortType", targetNamespace = "http://www.ericsson.com/esb/customer/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPortType {


    /**
     * 
     * @param updateCaseStatus
     * @return
     *     returns co.com.claro.ejb.mgl.ws.client.updateCaseStatus.UpdateCaseStatusResponseTYPE
     * @throws EricssonFault
     */
    @WebMethod(action = "http://www.ericsson.com/esb/message/customer/updateCaseStatus/v1.0")
    @WebResult(name = "updateCaseStatusResponse", targetNamespace = "http://www.ericsson.com/esb/message/customer/updateCaseStatusResponse/v1.0", partName = "updateCaseStatusResponse")
    public UpdateCaseStatusResponseTYPE updateCaseStatus(
        @WebParam(name = "updateCaseStatusRequest", targetNamespace = "http://www.ericsson.com/esb/message/customer/updateCaseStatusRequest/v1.0", partName = "updateCaseStatus")
        UpdateCaseStatusType updateCaseStatus)
        throws EricssonFault
    ;

}
