
package co.com.claro.ejb.mgl.ws.client.updateCaseStatus;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ericssonFault", targetNamespace = "http://www.ericsson.com/esb/data/generico/CommonTypes/v2/")
public class EricssonFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EricssonFaultMessageType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EricssonFault(String message, EricssonFaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EricssonFault(String message, EricssonFaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.com.claro.ejb.mgl.ws.client.updateCaseStatus.EricssonFaultMessageType
     */
    public EricssonFaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
