
package com.oracle.xmlns.odi.odiinvoke.implement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.oracle.xmlns.odi.odiinvoke.service.OdiInvokeService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OdiInvoke", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", wsdlLocation = "http://odi-fulfill1-dev.claro.com.co:8420/oraclediagent-Fulfillment/OdiInvoke?wsdl")
public class OdiInvoke
    extends Service
{


    private final static QName ODIINVOKE_QNAME = new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvoke");



    public OdiInvoke(URL wsdlLocation) {
        super(wsdlLocation, ODIINVOKE_QNAME);
    }

    public OdiInvoke(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ODIINVOKE_QNAME, features);
    }

    public OdiInvoke(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OdiInvoke(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OdiInvokeService
     */
    @WebEndpoint(name = "OdiInvokeRequestSOAP11port0")
    public OdiInvokeService getOdiInvokeRequestSOAP11Port0() {
        return super.getPort(new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvokeRequestSOAP11port0"), OdiInvokeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OdiInvokeService
     */
    @WebEndpoint(name = "OdiInvokeRequestSOAP11port0")
    public OdiInvokeService getOdiInvokeRequestSOAP11Port0(WebServiceFeature... features) {
        return super.getPort(new QName("xmlns.oracle.com/odi/OdiInvoke/", "OdiInvokeRequestSOAP11port0"), OdiInvokeService.class, features);
    }



}
