
package com.amx.service.fulfilloper.exp.customerorder.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CustomerOrderSOAPBindingQSService", targetNamespace = "http://www.amx.com/service/FulFillOper/EXP/CustomerOrder/v1.0", wsdlLocation = "file:/C:/Azure/MER-FRONT/MGL/ServiceClientMGL/src/wsdl/100.123.246.43_8080/EXP_RSCusOrdeFeasibProfilingV1.0/PS_RSCusOrdeFeasibProfilingV1.0.wsdl")
public class CustomerOrderSOAPBindingQSService
    extends Service
{

    private final static URL CUSTOMERORDERSOAPBINDINGQSSERVICE_WSDL_LOCATION = null;
    private final static String ENDPOINT = "http://www.amx.com/service/FulFillOper/EXP/CustomerOrder/v1.0";
    private final static QName CUSTOMERORDERSOAPBINDINGQSSERVICE_QNAME = new QName(CustomerOrderSOAPBindingQSService.ENDPOINT, "CustomerOrderSOAPBindingQSService");
    

    public CustomerOrderSOAPBindingQSService() {
        super(__getWsdlLocation(), CUSTOMERORDERSOAPBINDINGQSSERVICE_QNAME);
    }

    public CustomerOrderSOAPBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }
    
    public CustomerOrderSOAPBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERORDERSOAPBINDINGQSSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns CustomerOrderInteface
     */
    @WebEndpoint(name = "CustomerOrderSOAPBindingQSPort")
    public ICustomerOrderInteface getCustomerOrderSOAPBindingQSPort() {
        return super.getPort(new QName("http://www.amx.com/service/FulFillOper/EXP/CustomerOrder/v1.0", "CustomerOrderSOAPBindingQSPort"), ICustomerOrderInteface.class);
    }

    private static URL __getWsdlLocation() {
        return CUSTOMERORDERSOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
