
package com.amx.service.fulfilloper.exp.customerorder.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import com.amx.schema.fulfilloper.exp.customerorder.v1.CustomerOrderRequest;
import com.amx.schema.fulfilloper.exp.customerorder.v1.CustomerOrderResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CustomerOrderInteface", targetNamespace = "http://www.amx.com/service/FulFillOper/EXP/CustomerOrder/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ICustomerOrderInteface {


    /**
     * 
     * @param in
     * @return
     *     returns com.amx.schema.fulfilloper.exp.customerorder.v1.CustomerOrderResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "CustomerOrder", action = "http://www.amx.com/service/FulFillOper/EXP/CustomerOrder/v1.0/CustomerOrder")
    @WebResult(name = "CustomerOrderResponse", targetNamespace = "http://www.amx.com/schema/FulFillOper/EXP/CustomerOrder/v1.0", partName = "out")
    public CustomerOrderResponse customerOrder(
        @WebParam(name = "CustomerOrderRequest", targetNamespace = "http://www.amx.com/schema/FulFillOper/EXP/CustomerOrder/v1.0", partName = "in")
        CustomerOrderRequest in)
        throws FaultMessage
    ;

}
