
package co.claro.wcc.services.upload.uploadcuentasmatrices;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "uploadCuentasMatrices", targetNamespace = "http://claro.co/wcc/services/upload/uploadCuentasMatrices", wsdlLocation = "http://localhost:18000/WSCuentasMatrices/uploadCuentasMatrices?WSDL")
public class UploadCuentasMatrices_Service
    extends Service
{

    private final static URL UPLOADCUENTASMATRICES_WSDL_LOCATION;
    private final static WebServiceException UPLOADCUENTASMATRICES_EXCEPTION;
    private final static QName UPLOADCUENTASMATRICES_QNAME = new QName("http://claro.co/wcc/services/upload/uploadCuentasMatrices", "uploadCuentasMatrices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18000/WSCuentasMatrices/uploadCuentasMatrices?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPLOADCUENTASMATRICES_WSDL_LOCATION = url;
        UPLOADCUENTASMATRICES_EXCEPTION = e;
    }

    public UploadCuentasMatrices_Service() {
        super(__getWsdlLocation(), UPLOADCUENTASMATRICES_QNAME);
    }

    public UploadCuentasMatrices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADCUENTASMATRICES_QNAME, features);
    }

    public UploadCuentasMatrices_Service(URL wsdlLocation) {
        super(wsdlLocation, UPLOADCUENTASMATRICES_QNAME);
    }

    public UploadCuentasMatrices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADCUENTASMATRICES_QNAME, features);
    }

    public UploadCuentasMatrices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadCuentasMatrices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UploadCuentasMatrices
     */
    @WebEndpoint(name = "uploadCuentasMatricesPort")
    public UploadCuentasMatrices getUploadCuentasMatricesPort() {
        return super.getPort(new QName("http://claro.co/wcc/services/upload/uploadCuentasMatrices", "uploadCuentasMatricesPort"), UploadCuentasMatrices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadCuentasMatrices
     */
    @WebEndpoint(name = "uploadCuentasMatricesPort")
    public UploadCuentasMatrices getUploadCuentasMatricesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.co/wcc/services/upload/uploadCuentasMatrices", "uploadCuentasMatricesPort"), UploadCuentasMatrices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADCUENTASMATRICES_EXCEPTION!= null) {
            throw UPLOADCUENTASMATRICES_EXCEPTION;
        }
        return UPLOADCUENTASMATRICES_WSDL_LOCATION;
    }

}
