
package co.claro.wcc.services.search.searchcuentasmatrices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "searchCuentasMatrices", targetNamespace = "http://claro.co/wcc/services/search/searchCuentasMatrices", wsdlLocation = "http://localhost:18000/WSCuentasMatrices/searchCuentasMatrices?WSDL")
public class SearchCuentasMatrices_Service
    extends Service
{

    private final static URL SEARCHCUENTASMATRICES_WSDL_LOCATION;
    private final static WebServiceException SEARCHCUENTASMATRICES_EXCEPTION;
    private final static QName SEARCHCUENTASMATRICES_QNAME = new QName("http://claro.co/wcc/services/search/searchCuentasMatrices", "searchCuentasMatrices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18000/WSCuentasMatrices/searchCuentasMatrices?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHCUENTASMATRICES_WSDL_LOCATION = url;
        SEARCHCUENTASMATRICES_EXCEPTION = e;
    }

    public SearchCuentasMatrices_Service() {
        super(__getWsdlLocation(), SEARCHCUENTASMATRICES_QNAME);
    }

    public SearchCuentasMatrices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHCUENTASMATRICES_QNAME, features);
    }

    public SearchCuentasMatrices_Service(URL wsdlLocation) {
        super(wsdlLocation, SEARCHCUENTASMATRICES_QNAME);
    }

    public SearchCuentasMatrices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHCUENTASMATRICES_QNAME, features);
    }

    public SearchCuentasMatrices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchCuentasMatrices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchCuentasMatrices
     */
    @WebEndpoint(name = "searchCuentasMatricesPort")
    public SearchCuentasMatrices getSearchCuentasMatricesPort() {
        return super.getPort(new QName("http://claro.co/wcc/services/search/searchCuentasMatrices", "searchCuentasMatricesPort"), SearchCuentasMatrices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchCuentasMatrices
     */
    @WebEndpoint(name = "searchCuentasMatricesPort")
    public SearchCuentasMatrices getSearchCuentasMatricesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.co/wcc/services/search/searchCuentasMatrices", "searchCuentasMatricesPort"), SearchCuentasMatrices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHCUENTASMATRICES_EXCEPTION!= null) {
            throw SEARCHCUENTASMATRICES_EXCEPTION;
        }
        return SEARCHCUENTASMATRICES_WSDL_LOCATION;
    }

}
