/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.claro.CMatricesAs400Service.war.restful;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author Alquiler
 */
@javax.ws.rs.ApplicationPath("location")
public class CmtApplicationConfigLocation extends Application {
    
    private static final Logger LOGGER = LogManager.getLogger(CmtApplicationConfigLocation.class);

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException e) {
            LOGGER.error("Error en getClasses. " +e.getMessage(), e); 
        }catch (Exception e) {
            LOGGER.error("Error en getClasses. " +e.getMessage(), e); 
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically
     * re-generated by NetBeans REST support to populate given list with all
     * resources defined in the project.
     */
    private void addRestResourceClasses(java.util.Set<java.lang.Class<?>> resources) {
        resources.add(co.com.claro.CMatricesAs400Service.war.restful.CmtLocationsRest.class);
    }
}
