
package co.claro.wcc.services.upload.ordenesservicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import co.claro.wcc.schema.schemaoperations.FileRequestType;
import co.claro.wcc.schema.schemaoperations.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "uploadOrdenesServicio", targetNamespace = "http://claro.co/wcc/services/upload/OrdenesServicio/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.claro.wcc.schema.schemadocument.ObjectFactory.class,
    co.claro.wcc.schema.schemaoperations.ObjectFactory.class
})
public interface UploadOrdenesServicio {


    /**
     * 
     * @param requestMessage
     * @return
     *     returns co.claro.wcc.schema.schemaoperations.ResponseType
     * @throws UploadOrdenesServicioFault
     */
    @WebMethod(action = "http://claro.co/wcc/services/upload/uploadOrdenesServicio/insert")
    @WebResult(name = "documentResponse", targetNamespace = "http://claro.co/wcc/schema/SchemaOperations", partName = "responseMessage")
    public ResponseType insert(
        @WebParam(name = "documentFileRequest", targetNamespace = "http://claro.co/wcc/schema/SchemaOperations", partName = "requestMessage")
        FileRequestType requestMessage)
        throws UploadOrdenesServicioFault
    ;

}
