
package net.telmex.unit.exceptions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PcmlException", targetNamespace = "http://unit.telmex.net/")
public class PcmlException_Exception
    extends Exception
{

    /**
	 * Serial de Version UID
	 */
	private static final long serialVersionUID = 1L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PcmlException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PcmlException_Exception(String message, PcmlException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PcmlException_Exception(String message, PcmlException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.telmex.unit.exceptions.PcmlException
     */
    public PcmlException getFaultInfo() {
        return faultInfo;
    }

}
