
package net.telmex.unit.management;

import net.telmex.unit.dto.ModifyResponse;
import net.telmex.unit.implement.ModifyUnitRequest;
import net.telmex.unit.exceptions.PcmlException_Exception;
import net.telmex.unit.factory.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "management", targetNamespace = "http://unit.telmex.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Management {

    /**
     * 
     * @param requestModUnit
     * @return
     *     returns net.telmex.unit.dto.ModifyResponse
     * @throws PcmlException_Exception
     */
    @WebMethod
    @WebResult(name = "responseModUnit", targetNamespace = "")
    @RequestWrapper(localName = "modifyUnit", targetNamespace = "http://unit.telmex.net/", className = "net.telmex.unit.implement.ModifyUnit")
    @ResponseWrapper(localName = "modifyUnitResponse", targetNamespace = "http://unit.telmex.net/", className = "net.telmex.unit.implement.ModifyUnitResponse")
    @Action(input = "http://unit.telmex.net/management/modifyUnitRequest", output = "http://unit.telmex.net/management/modifyUnitResponse", fault = {
        @FaultAction(className = PcmlException_Exception.class, value = "http://unit.telmex.net/management/modifyUnit/Fault/PcmlException")
    })
    public ModifyResponse modifyUnit(
        @WebParam(name = "requestModUnit", targetNamespace = "")
        ModifyUnitRequest requestModUnit)
        throws PcmlException_Exception
    ;


}
