
package com.oracle.xmlns.odi.odiinvoke.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import com.oracle.xmlns.odi.odiinvoke.dto.request.OdiStartLoadPlanRequest;
import com.oracle.xmlns.odi.odiinvoke.dto.response.OdiStartLoadPlanResponse;
import com.oracle.xmlns.odi.odiinvoke.factory.ObjectFactoryOdiInvoke;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "requestPortType", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactoryOdiInvoke.class
})
public interface OdiInvokeService {


    /** NO BORRAR
     * 
     * @param part1
     * @return
     *     returns com.oracle.xmlns.odi.odiinvoke.OdiStartLoadPlanResponse
     */
    @WebMethod(action = "xmlns.oracle.com/odi/OdiInvoke/invokeStartLoadPlan")
    @WebResult(name = "OdiStartLoadPlanResponse", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
    @Action(input = "xmlns.oracle.com/odi/OdiInvoke/invokeStartLoadPlan", output = "xmlns.oracle.com/odi/OdiInvoke/requestPortType/invokeStartLoadPlanResponse")
    public OdiStartLoadPlanResponse invokeStartLoadPlan(
        @WebParam(name = "OdiStartLoadPlanRequest", targetNamespace = "xmlns.oracle.com/odi/OdiInvoke/", partName = "part1")
        OdiStartLoadPlanRequest part1);


}
