
package co.com.telmex.catastro.services.wservicelocal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsSitidataStandar", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSitidataStandar {


    /**
     * 
     * @param address
     * @param state
     * @param district
     * @param password
     * @param user
     * @param city
     * @return
     *     returns co.com.telmex.catastro.services.wservicelocal.ReturnDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrich", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.Enrich")
    @ResponseWrapper(localName = "enrichResponse", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.EnrichResponse")
    public ReturnDto enrich(
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "district", targetNamespace = "")
        String district,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param address
     * @param state
     * @param district
     * @param password
     * @param user
     * @param city
     * @return
     *     returns co.com.telmex.catastro.services.wservicelocal.ReturnDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrichAssist", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.EnrichAssist")
    @ResponseWrapper(localName = "enrichAssistResponse", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.EnrichAssistResponse")
    public ReturnDto enrichAssist(
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "district", targetNamespace = "")
        String district,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param xmlSend
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrichXmlBatch", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.EnrichXmlBatch")
    @ResponseWrapper(localName = "enrichXmlBatchResponse", targetNamespace = "http://service.sitidata.encapsular.claro.com.co/", className = "co.com.telmex.catastro.services.wservicelocal.EnrichXmlBatchResponse")
    public String enrichXmlBatch(
        @WebParam(name = "xmlSend", targetNamespace = "")
        String xmlSend,
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
