
package com.amx.service.automaticclosingonyx.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "automaticClosingOnyxSoapBindingQSService", targetNamespace = "http://www.amx.com/Service/automaticClosingOnyx/v1.0", wsdlLocation = "http://172.24.42.211:8001/EXP_automaticClosingONYX/PS_automaticClosingONYXV1.0?wsdl")
public class AutomaticClosingOnyxSoapBindingQSService
    extends Service
{

    private final static URL AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_EXCEPTION;
    private final static QName AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_QNAME = new QName("http://www.amx.com/Service/automaticClosingOnyx/v1.0", "automaticClosingOnyxSoapBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.24.42.211:8001/EXP_automaticClosingONYX/PS_automaticClosingONYXV1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
        AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_EXCEPTION = e;
    }

    public AutomaticClosingOnyxSoapBindingQSService() {
        super(__getWsdlLocation(), AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_QNAME);
    }

    public AutomaticClosingOnyxSoapBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_QNAME, features);
    }

    public AutomaticClosingOnyxSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_QNAME);
    }

    public AutomaticClosingOnyxSoapBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_QNAME, features);
    }

    public AutomaticClosingOnyxSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomaticClosingOnyxSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutomaticClosingOnyxInterface
     */
    @WebEndpoint(name = "automaticClosingOnyxSoapBindingQSPort")
    public AutomaticClosingOnyxInterface getAutomaticClosingOnyxSoapBindingQSPort() {
        return super.getPort(new QName("http://www.amx.com/Service/automaticClosingOnyx/v1.0", "automaticClosingOnyxSoapBindingQSPort"), AutomaticClosingOnyxInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomaticClosingOnyxInterface
     */
    @WebEndpoint(name = "automaticClosingOnyxSoapBindingQSPort")
    public AutomaticClosingOnyxInterface getAutomaticClosingOnyxSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.amx.com/Service/automaticClosingOnyx/v1.0", "automaticClosingOnyxSoapBindingQSPort"), AutomaticClosingOnyxInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_EXCEPTION!= null) {
            throw AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_EXCEPTION;
        }
        return AUTOMATICCLOSINGONYXSOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
