
package com.amx.service.automaticclosingonyx.v1;



import co.com.claro.visitastecnicas.ws.proxy.HeaderRequest;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.amx.service.exp.operation.mernotify.v1.MERNotifyRequestType;
import com.amx.service.exp.operation.mernotify.v1.MERNotifyResponseType;
import com.amx.service.exp.operation.updateclosingtask.v1.UpdateClosingTaskRequest;
import com.amx.service.exp.operation.updateclosingtask.v1.UpdateClosingTaskResponse;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "automaticClosingOnyxInterface", targetNamespace = "http://www.amx.com/Service/automaticClosingOnyx/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.amx.service.exp.operation.updateclosingtask.v1.ObjectFactory.class,
    com.amx.service.exp.operation.mernotify.v1.ObjectFactory.class,
    com.amx.co.schema.claroheaders.v1.ObjectFactory.class,
    com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.ObjectFactory.class
})
public interface AutomaticClosingOnyxInterface {


    /**
     * 
     * @param body
     * @return
     *     returns com.amx.service.exp.operation.mernotify.v1.MERNotifyResponseType
     * @throws FaultMessage
     */
    @WebMethod(operationName = "MERNotify", action = "MERNotify")
    @WebResult(name = "MERNotifyResponse", targetNamespace = "http://www.amx.com/Service/exp/Operation/MERNotify/v1.0", partName = "body")
    @RequestWrapper(localName = "headerRequest", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", className = "com.amx.co.schema.claroheaders.v1.HeaderRequest", partName = "headerRequest")
    @ResponseWrapper(localName = "headerResponse", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", className = "com.amx.co.schema.claroheaders.v1.HeaderResponse", partName = "headerResponse")
    public MERNotifyResponseType merNotify(
        @WebParam(name = "headerRequest", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", header = true, partName = "headerRequest") HeaderRequest headerRequest,    
        @WebParam(name = "MERNotifyRequest", targetNamespace = "http://www.amx.com/Service/exp/Operation/MERNotify/v1.0", partName = "body")
        MERNotifyRequestType body) throws FaultMessage;

    /**
     * 
     * @param body
     * @return
     *     returns com.amx.service.exp.operation.updateclosingtask.v1.UpdateClosingTaskResponse
     * @throws FaultMessage
     */
    @WebMethod(operationName = "updateClosingTask", action = "updateClosingTask")
    @WebResult(name = "updateClosingTaskResponse", targetNamespace = "http://www.amx.com/Service/exp/Operation/updateClosingTask/v1.0", partName = "body")
    @RequestWrapper(localName = "headerRequest", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", className = "com.amx.co.schema.claroheaders.v1.HeaderRequest", partName = "headerRequest")
    @ResponseWrapper(localName = "headerResponse", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", className = "com.amx.co.schema.claroheaders.v1.HeaderResponse", partName = "headerResponse")
    public UpdateClosingTaskResponse updateClosingTask(
            @WebParam(name = "headerRequest", targetNamespace = "http://www.amx.com/CO/Schema/ClaroHeaders/v1", header = true, partName = "headerRequest") HeaderRequest headerRequest,
            @WebParam(name = "updateClosingTaskRequest", targetNamespace = "http://www.amx.com/Service/exp/Operation/updateClosingTask/v1.0", partName = "body") UpdateClosingTaskRequest body) throws FaultMessage;

}
