
package com.amx.service.automaticclosingonyx.v1;

import javax.xml.ws.WebFault;
import com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.FaultMessageType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FaultMessage", targetNamespace = "http://www.amx.com/co/schema/mobile/common/aplicationIntegration/Comunes/v1.0")
public class FaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultMessageType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultMessage(String message, FaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultMessage(String message, FaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.amx.co.schema.mobile.common.aplicationintegration.comunes.v1.FaultMessageType
     */
    public FaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
