
package co.claro.wcc.services.search.ordenesservicio;

import javax.xml.ws.WebFault;
import co.claro.wcc.schema.schemaoperations.FaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "faultResponse", targetNamespace = "http://claro.co/wcc/schema/SchemaOperations")
public class SearchOrdenesServicioFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SearchOrdenesServicioFault(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SearchOrdenesServicioFault(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.claro.wcc.schema.schemaoperations.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
