
package co.claro.wcc.services.search.ordenesservicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import co.claro.wcc.schema.schemaoperations.RequestType;
import co.claro.wcc.schema.schemaoperations.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "searchOrdenesServicio", targetNamespace = "http://claro.co/wcc/services/search/OrdenesServicio/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.claro.wcc.schema.schemadocument.ObjectFactory.class,
    co.claro.wcc.schema.schemaoperations.ObjectFactory.class
})
public interface SearchOrdenesServicio {


    /**
     * 
     * @param requestMessage
     * @return
     *     returns co.claro.wcc.schema.schemaoperations.ResponseType
     * @throws SearchOrdenesServicioFault
     */
    @WebMethod(action = "http://claro.co/wcc/services/search/searchOrdenesServicio/find")
    @WebResult(name = "documentResponse", targetNamespace = "http://claro.co/wcc/schema/SchemaOperations", partName = "responseMessage")
    public ResponseType find(
        @WebParam(name = "documentRequest", targetNamespace = "http://claro.co/wcc/schema/SchemaOperations", partName = "requestMessage")
        RequestType requestMessage)
        throws SearchOrdenesServicioFault
    ;

}
