
package net.telmex.unit.implement;

import net.telmex.unit.management.Management;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnitService", targetNamespace = "http://unit.telmex.net/", wsdlLocation = "http://100.123.246.49:8080/UnitService/management?wsdl")
public class UnitService
    extends Service
{

    private final static QName UNITSERVICE_QNAME = new QName("http://unit.telmex.net/", "UnitService");


    public UnitService(URL wsdlLocation) {
        super(wsdlLocation, UNITSERVICE_QNAME);
    }

    public UnitService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNITSERVICE_QNAME, features);
    }

    public UnitService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnitService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Management
     */
    @WebEndpoint(name = "managementPort")
    public Management getManagementPort() {
        return super.getPort(new QName("http://unit.telmex.net/", "managementPort"), Management.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Management
     */
    @WebEndpoint(name = "managementPort")
    public Management getManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://unit.telmex.net/", "managementPort"), Management.class, features);
    }


}
