
package com.amx.service.massivefailures.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MassiveFailureSoapBindingQSService", targetNamespace = "http://www.amx.com/Service/MassiveFailures/V1.0", wsdlLocation = "http://172.24.42.211:8002/MassiveFailures/V1.0?wsdl")
public class MassiveFailureSoapBindingQSService
    extends Service
{

    private final static URL MASSIVEFAILURESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MASSIVEFAILURESOAPBINDINGQSSERVICE_EXCEPTION;
    private final static QName MASSIVEFAILURESOAPBINDINGQSSERVICE_QNAME = new QName("http://www.amx.com/Service/MassiveFailures/V1.0", "MassiveFailureSoapBindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.24.42.211:8002/MassiveFailures/V1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASSIVEFAILURESOAPBINDINGQSSERVICE_WSDL_LOCATION = url;
        MASSIVEFAILURESOAPBINDINGQSSERVICE_EXCEPTION = e;
    }

    public MassiveFailureSoapBindingQSService() {
        super(__getWsdlLocation(), MASSIVEFAILURESOAPBINDINGQSSERVICE_QNAME);
    }

    public MassiveFailureSoapBindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MASSIVEFAILURESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public MassiveFailureSoapBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, MASSIVEFAILURESOAPBINDINGQSSERVICE_QNAME);
    }

    public MassiveFailureSoapBindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MASSIVEFAILURESOAPBINDINGQSSERVICE_QNAME, features);
    }

    public MassiveFailureSoapBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MassiveFailureSoapBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MassiveFailure
     */
    @WebEndpoint(name = "MassiveFailureSoapBindingQSPort")
    public MassiveFailure getMassiveFailureSoapBindingQSPort() {
        return super.getPort(new QName("http://www.amx.com/Service/MassiveFailures/V1.0", "MassiveFailureSoapBindingQSPort"), MassiveFailure.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MassiveFailure
     */
    @WebEndpoint(name = "MassiveFailureSoapBindingQSPort")
    public MassiveFailure getMassiveFailureSoapBindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.amx.com/Service/MassiveFailures/V1.0", "MassiveFailureSoapBindingQSPort"), MassiveFailure.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASSIVEFAILURESOAPBINDINGQSSERVICE_EXCEPTION!= null) {
            throw MASSIVEFAILURESOAPBINDINGQSSERVICE_EXCEPTION;
        }
        return MASSIVEFAILURESOAPBINDINGQSSERVICE_WSDL_LOCATION;
    }

}
