
package com.amx.service.massivefailures.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.amx.schema.operation.getmassivefailurerequest.v1.GetMassiveFailureRequest;
import com.amx.schema.operation.getmassivefailurerequest.v1.GetMassiveFailureResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-740-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MassiveFailure", targetNamespace = "http://www.amx.com/Service/MassiveFailures/V1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.amx.co.schema.claroheaders.v1.ObjectFactory.class,
    com.amx.co.schema.clarofault.v1.ObjectFactory.class,
    com.amx.schema.operation.getmassivefailurerequest.v1.ObjectFactory.class
})
public interface MassiveFailure {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.amx.schema.operation.getmassivefailurerequest.v1.GetMassiveFailureResponse
     */
    @WebMethod
    @WebResult(name = "GetMassiveFailureResponse", targetNamespace = "http://www.amx.com/Schema/Operation/GetMassiveFailureRequest/V1.0", partName = "parameters")
    public GetMassiveFailureResponse getMassiveFailureRequest(
        @WebParam(name = "GetMassiveFailureRequest", targetNamespace = "http://www.amx.com/Schema/Operation/GetMassiveFailureRequest/V1.0", partName = "parameters")
        GetMassiveFailureRequest parameters);

}
