/*
 * Copyright (c) 2017, and/or its affiliates. All rights reserved.
 * CLARO PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package co.com.claro.mgl.mbeans.vt.migracion.beans.enums;

/**
 * Objetivo:
 *
 * Descripción:
 * 
 * @author becerraarmr
 *
 * @version 1.0 revisión 1.0
 */
public enum  AccionesVT{
  INDEX,
  SOLICITAR_VT_EDIFICIO_CONJUNTO,
  SOLICITAR_VT_REPLANTEAMIENTO,
  SOLICITAR_VT_EN_CASA,
  SOLICITAR_CREACION_CUENTA_MATRIZ,
  SOLICITAR_CREACION_HHPP_UNIDIRECCIONAL,
  SOLICITAR_CREACION_HHPP_EN_CUENTA_MATRIZ,
  SOLICITAR_ACTUALIZACION_CAMBIO_ESTRATO,
  SOLICITAR_MODIFICAR_ELIMINACION_CUENTA_MATRIZ,
  SOLICITAR_MODIFICAR_HHPP,
  SOLICITAR_VERIFICACION_CASAS,
  SOLICITAR_VIABILIDAD_INTERNET,
  SOLICITAR_CAMBIO_ESTRATO,
  GESTIONAR_VT_EDIFICIO_CONJUNTO,
  GESTIONAR_VT_REPLANTEAMIENTO,
  GESTIONAR_VT_EN_CASAS,
  GESTIONAR_CREACION_CUENTA_MATRIZ,
  GESTIONAR_CREACION_HHPP_UNIDIRECCIONAL,
  GESTIONAR_CREACION_HHPP_EN_CUENTA_MATRIZ,
  GESTIONAR_ACTUALIZACION_CAMBIO_ESTRATO,
  GESTIONAR_MODIFICAR_ELIMINAR_CUENTA_MATRIZ,
  GESTIONAR_ACTUALIZACION_HHPP,
  GESTIONAR_VERIFICACION_CASAS,
  GESTIONAR_VIABILIDAD_INTERNET,
  GESTIONAR_CAMBIO_ESTRATO,
  ESTADO_SOLICITUD,
  ADMINISTRADOR,
  REPORTES_SOLICITUDES,
  CIERRE_MASIVO,
  ADMINISTRADOR_DE_DIRECCIONES_NODO,
  ADMINISTRADOR_DE_DIRECCIONES_HHPP,
  ADMINISTRADOR_DE_DIRECCIONES_DIRECCION,
  ADMINISTRADOR_DE_DIRECCIONES_DPTO_CIUDADES,
  OPERACIONES_HHPP_CAMBIO_ESTRATO_MASIVO,
  OPERACIONES_HHPP_ELIMINAR_MASIVAMENTE_HHPP
}
