
package co.com.claro.wsresourcehomepass.service;

import co.com.claro.wsresourcehomepass.headers.HeaderRequest;
import co.com.claro.wsresourcehomepass.headers.HeaderResponse;
import co.com.claro.wsresourcehomepass.factory.ObjectFactory;
import co.com.claro.wsresourcehomepass.implement.ValidateReactivationResource;
import co.com.claro.wsresourcehomepass.implement.ValidateReactivationResourceResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {

    /**
     * 
     * @param headerRequest
     * @param headerResponse
     * @param parameters
     * @return
     *     returns co.com.claro.wsresourcehomepass.implement.ValidateReactivationResourceResponse
     */
    @WebMethod(operationName = "ValidateReactivationResource")
    @WebResult(name = "ValidateReactivationResourceResponse", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://implement.wsresourcehomepass.claro.com.co/Service/ValidateReactivationResourceRequest", output = "http://implement.wsresourcehomepass.claro.com.co/Service/ValidateReactivationResourceResponse")
    public ValidateReactivationResourceResponse validateReactivationResource(
        @WebParam(name = "ValidateReactivationResource", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/", partName = "parameters")
        ValidateReactivationResource parameters,
        @WebParam(name = "headerRequest", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/", header = true, partName = "headerRequest")
        HeaderRequest headerRequest,
        @WebParam(name = "headerResponse", targetNamespace = "http://implement.wsresourcehomepass.claro.com.co/", header = true, mode = WebParam.Mode.OUT, partName = "headerResponse")
        Holder<HeaderResponse> headerResponse);

}
